### ISSUE TITLE
Assginment 4 Issues/Questions

### ISSUE THREAD

**Issue by neuralinfo** [MIDS-W205/Assignments#3]
Write your issues/questions about assignment 1 here

**Comment by samacart** [comment]
Hi Arash - from my understanding the Twitter search API only allows you to go back 10 days (via Tweepy or any other library). Looking at the URL you posted on the comments I can see that the information exists, but we cannot access it via the Twitter search API. 

The only thought I have is to use the URL you provided and then screen scrape to identify the tweet text. 

Is this your expectation, or have I missed something obvious?

Thanks,
Simon.

**Comment by MIDS-W205** [comment]
Twitter keeps tweets from 2006. However, the search API does not provide
the index of all tweets since 2006. The search API index typically includes
between 6-9 days of tweets depending on how popular a tweet is. You need to
address this constraint by finding other alternatives. Whether you scrape
the twitter web search API or utilize services that provide twitter
historical data such as topsy is your design decision.

Suggestion: Begin working on the assignment by gathering at least one week
of tweets using the search API and use them for your codes in other tasks.
Simultaneously, you can think of ways that allow you to gather such
historical data.

**Comment by MIDS-W205** [comment]
Twitter keeps tweets from 2006. However, the search API does not provide the index of all tweets since 2006. The search API index typically includes between 6-9 days of tweets depending on how popular a tweet is. You need to address this constraint by finding other alternatives. Whether you scrape the twitter web search API or utilize services that provide twitter historical data such as topsy is your design decision. 

Suggestion: Begin working on the assignment by gathering at least one week of tweets using the search API and use them for your codes in other tasks. Simultaneously, you can think of ways that allow you to gather such historical data.

**Comment by samacart** [comment]
Thanks Arash - from my reading it appears Topsy is no longer accepting new clients. I thought I'd post that here to save others from searching.

**Comment by qyjoan** [comment]
Need some help on analysis 4 and the bonus, mainly on understanding. Based on the description of 4, since we are interested in the number of occurrence  of "other" words, in the example we have here:

"I have seen Brazil match today. I am so happy that they won"

1. in the output, is it correct that we do not need to say "I occurs 1 time with I"? 
2. again, using the same example, the output is not symmetric based on how we count "co-occurrence". For example, "I occurs 1 time with Brazil", but "Brazil occurs 2 times with I"?
3. Because of my confusion about 2, I'm not able to translate PMI in the conditional frequency context . Let's say, I have two tweets, one is the one above, and another one being

"The weather in Brazil is very nice today"

If I want to consider the PMI(I, Brazil). How do I use the result of the previous part? According to wiki, it should be symmetric, i.e. PMI(I,brazil) = PMI(brazil, I) = c(brazil, I) / (c(brazil)*c(i)). However, c(brazil, I) != c(i, brazil) according to the part 4.

I'm sure I'm missing something here...would really appreciate if someone and shed some light on this. Thanks!

**Comment by MIDS-W205** [comment]
Answer to your question:
1.Yes.
2.  With the word Brazil, I occurs twice and with the word I, Brazil occurs once. This is different than PMI and your program for task 4 should calculate this not PMI.
3. You can not use the results from task 4 for 5. You need to modify it to compute the PMI. To be more specific for PMI, if a tweet contains Brazil, Brazil, I; then there are not two occurrences of Brazil and I appearing together. There is only one.

**Comment by julian-phillips** [comment]
Is it ok to partition the tweets into different files on S3 rather than having one csv file?  I assume this should not effect the EMR job, but I just want to check.

**Comment by MIDS-W205** [comment]
If the input files are big, then it is recommended to split them to smaller sizes to get a better performance. Other than that, the input split does not have any effect on the EMR job flow

**Comment by julian-phillips** [comment]
Clarification on Joans question.
With "I have seen Brazil match today. I am so happy that they won.
With Brazil, I occurs twice.
With I Brazil occurs once.

However, I occurs twice in the sentence, so when you iterate to the second instance of I you get it again, meaning on the map reduce they will be symmetrical.

For instance, in the sentence Brazil beat Brazil if you iterate through:
1) Brazil occurs with beat once.
2) Beat occurs with Brazil twice
3) Brazil occurs with beat once.

MR:
Brazil occurs with beat twice
Beat occurs with Brazil twice.

So do you want just unique occurances of each word then?

**Comment by MIDS-W205** [comment]
The instruction says: "for each word in the tweets' text, compute the occurrences of other words appear in every tweet that it appeared"

In your example,  

with Brazil, beat occurs once. 
with beat, Brazil occurs twice.
with Brazil, Brazil occurs once (not zero or two)

Hope it is clear now.

**Comment by julian-phillips** [comment]
Ok, I get that.  One more question.

What if the sentence was "brazil beat brazil in brazil"
Now brazil occurs with brazil twice?

**Comment by MIDS-W205** [comment]
Yes. regardless of  which Brazil you choose in the sentence,with Brazil, Brazil occurs twice in this text.
